# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_window.ui'
#
# Created: Thu Aug 11 11:40:54 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(300, 320)
        MainWindow.setMinimumSize(QtCore.QSize(300, 320))
        MainWindow.setBaseSize(QtCore.QSize(300, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/calc.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 200))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalFrame = QtGui.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(0, 0, 281, 291))
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.horizontalFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.display = QtGui.QLineEdit(self.horizontalFrame)
        self.display.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setReadOnly(True)
        self.display.setObjectName(_fromUtf8("display"))
        self.verticalLayout.addWidget(self.display)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self._2 = QtGui.QGridLayout()
        self._2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self._2.setSpacing(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.button_7 = QtGui.QPushButton(self.horizontalFrame)
        self.button_7.setMinimumSize(QtCore.QSize(40, 40))
        self.button_7.setMaximumSize(QtCore.QSize(40, 40))
        self.button_7.setObjectName(_fromUtf8("button_7"))
        self._2.addWidget(self.button_7, 0, 0, 1, 1)
        self.button_1 = QtGui.QPushButton(self.horizontalFrame)
        self.button_1.setMaximumSize(QtCore.QSize(40, 40))
        self.button_1.setObjectName(_fromUtf8("button_1"))
        self._2.addWidget(self.button_1, 2, 0, 1, 1)
        self.button_4 = QtGui.QPushButton(self.horizontalFrame)
        self.button_4.setMaximumSize(QtCore.QSize(40, 40))
        self.button_4.setObjectName(_fromUtf8("button_4"))
        self._2.addWidget(self.button_4, 1, 0, 1, 1)
        self.button_9 = QtGui.QPushButton(self.horizontalFrame)
        self.button_9.setMinimumSize(QtCore.QSize(40, 40))
        self.button_9.setMaximumSize(QtCore.QSize(40, 40))
        self.button_9.setObjectName(_fromUtf8("button_9"))
        self._2.addWidget(self.button_9, 0, 2, 1, 1)
        self.button_8 = QtGui.QPushButton(self.horizontalFrame)
        self.button_8.setMaximumSize(QtCore.QSize(40, 40))
        self.button_8.setObjectName(_fromUtf8("button_8"))
        self._2.addWidget(self.button_8, 0, 1, 1, 1)
        self.button_5 = QtGui.QPushButton(self.horizontalFrame)
        self.button_5.setMaximumSize(QtCore.QSize(40, 40))
        self.button_5.setObjectName(_fromUtf8("button_5"))
        self._2.addWidget(self.button_5, 1, 1, 1, 1)
        self.button_6 = QtGui.QPushButton(self.horizontalFrame)
        self.button_6.setMaximumSize(QtCore.QSize(40, 40))
        self.button_6.setObjectName(_fromUtf8("button_6"))
        self._2.addWidget(self.button_6, 1, 2, 1, 1)
        self.button_2 = QtGui.QPushButton(self.horizontalFrame)
        self.button_2.setMaximumSize(QtCore.QSize(39, 40))
        self.button_2.setObjectName(_fromUtf8("button_2"))
        self._2.addWidget(self.button_2, 2, 1, 1, 1)
        self.button_3 = QtGui.QPushButton(self.horizontalFrame)
        self.button_3.setMaximumSize(QtCore.QSize(40, 40))
        self.button_3.setObjectName(_fromUtf8("button_3"))
        self._2.addWidget(self.button_3, 2, 2, 1, 1)
        self.button_0 = QtGui.QPushButton(self.horizontalFrame)
        self.button_0.setMaximumSize(QtCore.QSize(40, 40))
        self.button_0.setObjectName(_fromUtf8("button_0"))
        self._2.addWidget(self.button_0, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self._2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.buttonCE = QtGui.QPushButton(self.horizontalFrame)
        self.buttonCE.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonCE.setObjectName(_fromUtf8("buttonCE"))
        self.verticalLayout_3.addWidget(self.buttonCE)
        self.buttonPlus = QtGui.QPushButton(self.horizontalFrame)
        self.buttonPlus.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonPlus.setObjectName(_fromUtf8("buttonPlus"))
        self.verticalLayout_3.addWidget(self.buttonPlus)
        self.buttonMinus = QtGui.QPushButton(self.horizontalFrame)
        self.buttonMinus.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonMinus.setObjectName(_fromUtf8("buttonMinus"))
        self.verticalLayout_3.addWidget(self.buttonMinus)
        self.buttonMult = QtGui.QPushButton(self.horizontalFrame)
        self.buttonMult.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonMult.setObjectName(_fromUtf8("buttonMult"))
        self.verticalLayout_3.addWidget(self.buttonMult)
        self.buttonDiv = QtGui.QPushButton(self.horizontalFrame)
        self.buttonDiv.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDiv.setObjectName(_fromUtf8("buttonDiv"))
        self.verticalLayout_3.addWidget(self.buttonDiv)
        self.buttonRes = QtGui.QPushButton(self.horizontalFrame)
        self.buttonRes.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonRes.setObjectName(_fromUtf8("buttonRes"))
        self.verticalLayout_3.addWidget(self.buttonRes)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_7, self.button_8)
        MainWindow.setTabOrder(self.button_8, self.button_9)
        MainWindow.setTabOrder(self.button_9, self.button_4)
        MainWindow.setTabOrder(self.button_4, self.button_5)
        MainWindow.setTabOrder(self.button_5, self.button_6)
        MainWindow.setTabOrder(self.button_6, self.button_1)
        MainWindow.setTabOrder(self.button_1, self.button_2)
        MainWindow.setTabOrder(self.button_2, self.button_3)
        MainWindow.setTabOrder(self.button_3, self.button_0)
        MainWindow.setTabOrder(self.button_0, self.buttonCE)
        MainWindow.setTabOrder(self.buttonCE, self.buttonPlus)
        MainWindow.setTabOrder(self.buttonPlus, self.buttonMinus)
        MainWindow.setTabOrder(self.buttonMinus, self.buttonMult)
        MainWindow.setTabOrder(self.buttonMult, self.buttonDiv)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.button_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.button_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.button_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.button_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.button_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.button_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.button_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.button_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCE.setText(QtGui.QApplication.translate("MainWindow", "CE", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlus.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMinus.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMult.setText(QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDiv.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRes.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

import calculator_rc
